AWSTemplateFormatVersion: "2010-09-09"
Description: "ECS Service Soundflow web application"

Parameters:
  PublicSubnet:
    Type: String
    Description: ID of the public subnet from Network stack
  ContainerSG:
    Type: String
    Description: Security Group ID for the ECS container


Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: Soundflow-cluster
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT
      Tags:
        - Key: Name
          Value: Soundflow-cluster

  LogGroup:
    Type: AWS::ECS::LogGroup
    Properties:
      LogGroupName: /ecs/Soundflow-service
      RetentionInDays: 30

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Path: /

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      Path: /
  
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: soundflow-task
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
          - Name: soundflow-container
            Image: !Join [ ":", [ !ImportValue SoundflowRepositoryUri, "latest" ] ]
            PortMappings:
              - ContainerPort: 3000
            Essential: true

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicSubnet
          SecurityGroups:
            - !Ref ContainerSG